---
- name: 'Install mysql'
  apt:
    name: ['python-mysqldb', 'mysql-server-5.6']
    state: latest
  become: yes

- name: 'Creating database MySQL'
  mysql_db:
    name: "{{ db_name }}"
    login_user: root
    state: present
  become: yes

- name: 'Creating a user into the database'
  mysql_user:
    login_user: root
    name: "{{ db_name }}"
    password: "{{ db_password }}"
    priv: '{{ db_name }}.*:ALL'
    state: present
    host: "{{ item }}"
  with_items:
    - "{{ db_ip }}" # ip mysql server
  become: yes

- name: 'MySQL config files'
  template:
    src: templates/my.cnf.j2
    dest: /etc/mysql/mysql.cnf
  become: yes
  notify:
    - restart mysql