---
- hosts: database
  handlers:
    - name: restart mysql
      service: 
        name: mysql
        state: restarted
      become: yes

  tasks:
    - name: 'Install mysql'
      apt:
        name: ['python3-mysqldb', 'mysql-server']
        state: latest
      become: yes

    - name: 'Creating database MySQL'
      mysql_db:
        name: wordpress_db
        login_user: root
        state: present
      become: yes

    - name: 'Creating a user into the database'
      mysql_user:
        login_user: root
        name: "{{ db_name }}"
        password: "{{ db_password }}"
        priv: 'wordpress_db.*:ALL'
        state: present
        host: "{{ item }}"
      with_items:
        - 'localhost'
        - '127.0.0.1'
        - "{{ db_ip }}" # ip mysql server
      become: yes
    
    - name: 'MySQL config files'
      template:
        src: my.j2
        dest: /etc/mysql/my.cnf
      become: yes
      notify:
        - restart mysql
  
- hosts: wordpress

  handlers:
    - name: restating apache daemon
      service:
        name: apache2
        state: restarted
      become: yes

  tasks:
    - name: 'Install packages'
      apt:
        name: ['php', 'libapache2-mod-php', 'php-mysql', 'php-curl', 'php-gd', 
               'php-mbstring', 'php-xml', 'php-xmlrpc', 'php-soap', 
               'php-intl', 'php-zip', 'apache2']
        state: latest
      become: yes

    - name: 'Download wordpress'
      get_url:
        url: https://wordpress.org/latest.tar.gz'
        dest: '/tmp/wordpress.tar.gz'
    
    - name: 'Unzip the wordpress'
      unarchive:
        src: '/tmp/wordpress.tar.gz'
        dest: '/var/www/'
        remote_src: yes
      become: yes
    
    - name: 'Creating the wp-config file in the server with template'
      template:
        src: wp-config.j2
        dest: "{{ wp_path_server }}wp-config.php"
      become: yes

    - name: 'Apache serving the wordpress'
      template:
        src: 000-default.j2
        dest: /etc/apache2/sites-enabled/000-default.conf
      become: yes
      notify:
        - restating apache daemon