---
- hosts: database
  vars:
    db_name: 'wordpress_db'
    db_user: 'wordpress_user'
    db_password: '12345' #do not use in production

  tasks:
    - name: 'Install mysql'
      apt:
        name: ['python3-mysqldb', 'mysql-server']
        state: latest
      become: yes

    - name: 'Creating database MySQL'
      mysql_db:
        name: wordpress_db
        login_user: root
        state: present
      become: yes

    - name: 'Creating a user into the database'
      mysql_user:
        login_user: root
        name: "{{ db_name }}"
        password: "{{ db_password }}"
        priv: 'wordpress_db.*:ALL'
        state: present
      become: yes
  
- hosts: wordpress
  vars:
    db_name: 'wordpress_db'
    db_user: 'wordpress_user'
    db_password: '12345' #do not use in production
    wordpress_path: '/var/www/wordpress/'

  handlers:
    - name: restating apache daemon
      service:
        name: apache2
        state: restarted
      become: yes

  tasks:
    - name: 'Install packages'
      apt:
        name: ['php', 'libapache2-mod-php', 'php-mysql', 'php-curl', 'php-gd', 'php-mbstring', 'php-xml', 'php-xmlrpc', 'php-soap', 
        'php-intl', 'php-zip', 'apache2']
        state: latest
      become: yes

    - name: 'Download wordpress'
      get_url:
        url: https://wordpress.org/latest.tar.gz'
        dest: '/tmp/wordpress.tar.gz'
    
    - name: 'Unzip the wordpress'
      unarchive:
        src: '/tmp/wordpress.tar.gz'
        dest: '/var/www/'
        remote_src: yes
      become: yes
    
    - name: 'Creating the wp-config file in the server with template'
      template:
        src: wp-config.j2
        dest: /var/www/wordpress/wp-config.php
      become: yes

    - name: 'Apache serving the wordpress'
      template:
        src: 000-default.j2
        dest: /etc/apache2/sites-enabled/000-default.conf
      become: yes
      notify:
        - restating apache daemon