---
- name: 'Download wordpress'
  get_url:
    url: https://wordpress.org/latest.tar.gz'
    dest: '/tmp/wordpress.tar.gz'
  
- name: 'Unzip the wordpress'
  unarchive:
    src: '/tmp/wordpress.tar.gz'
    dest: '/var/www/'
    remote_src: yes
  become: yes
  
- name: 'Creating the wp-config file in the server with template'
  template:
    src: wp-config.j2
    dest: /var/www/wordpress/wp-config.php
  become: yes

- name: 'Apache serving the wordpress'
  template:
    src: 000-default.j2
    dest: /etc/apache2/sites-enabled/000-default.conf
  become: yes
  notify:
    - restating apache daemon